DROP DATABASE IF EXISTS youthSports; 

USE youthSports;

CREATE TABLE manager(
id INT NOT NULL PRIMARY KEY,
managerName VARCHAR(100) NOT NULL,
team VARCHAR(100) NOT NULL,
uniqueId VARCHAR(50) NOT NULL
); 

CREATE TABLE teamSchedule(
id INT NOT NULL PRIMARY KEY,
teamId VARCHAR(100) NOT NULL,
team VARCHAR(100) NOT NULL,
uniqueId VARCHAR(50) NOT NULL,
FOREIGN KEY(uniqueId)
REFERENCES manager(uniqueId)
);

CREATE TABLE member(
id INT NOT NULL PRIMARY KEY,
memberName VARCHAR(100),
team VARCHAR(100) NOT NULL,
uniqueId VARCHAR(50),
FOREIGN KEY(uniqueId)
REFERENCES teamSchedule(uniqueId)
);

CREATE TABLE post(
id INT NOT NULL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
post VARCHAR(300) NOT NULL,
postDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);